name: quan_ly_chi_tieu
description: Ứng dụng quản lý chi tiêu
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.20.2
  fl_chart: ^0.68.0
  device_preview: ^1.1.0
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8
  flutter_facebook_auth: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google-icon.png
    - assets/icons/facebook-icon.png
